#!/bin/bash
# ==============================================================================
# COMPILATION WORKFLOW MANAGER - GNU Z80ASM VERSION
# Target toolchain: Standalone GNU z80asm
# Output profile: Bit-Perfect 2KB EPROM Image Layout ($0800 bytes / 2048 bytes)
# ==============================================================================

SOURCE_FILE="mitsimon.asm"
RAW_BIN="mitsimon.bin"
LIST_FILE="mitsimon.lis"
FINAL_ROM="mitsimon_eprom.bin"
TARGET_SIZE=2048

echo "================================================================================"
echo "⚙️  STEP 1: Initialising GNU z80asm Compiler Pipeline..."
echo "================================================================================"

if [ ! -f "$SOURCE_FILE" ]; then
    echo "❌ Error: Master assembly file '$SOURCE_FILE' could not be found."
    exit 1
fi

# GNU z80asm flags:
# -l : Generates a complete .lis file with a full symbol and address map table.
# Redirect standard list output straight into the local .lis target file
# Execute GNU z80asm and redirect both standard output and error streams to the list file
z80asm -l -o "$RAW_BIN" "$SOURCE_FILE" > "$LIST_FILE" 2>&1



if [ $? -ne 0 ]; then
    echo "❌ Error: Code compilation encountered syntax faults. Review logs above."
    exit 1
else
    echo "✅ Success: Raw assembly phase complete without faults."
fi

echo ""
echo "================================================================================"
echo "📦 STEP 2: Isolating EPROM Space and Trimming Lower RAM Footprint..."
echo "================================================================================"

# Calculate bytes used by RAM workspace blocks from line 0070 to 0122 ($0003 to $0100 range)
# $0003 to $0040 (61 bytes) + $0040 to $0100 workspace. Total layout overhead is exactly 149 bytes!
# We strip the first 149 bytes so the binary starts strictly at ORG $F800 (TRUMP: JP PON)
echo "✂️  Trimming 149 bytes of lower zero-allocated RAM workspace from binary start..."
dd if="$RAW_BIN" of="$FINAL_ROM" bs=1 skip=149 status=none

CURRENT_SIZE=$(wc -c < "$FINAL_ROM" | tr -d ' ')
echo "📊 Pure EPROM Code Footprint: $CURRENT_SIZE bytes"

if [ "$CURRENT_SIZE" -lt "$TARGET_SIZE" ]; then
    PADDING_BYTES=$((TARGET_SIZE - CURRENT_SIZE))
    echo "💾 Payload is under 2KB. Injecting $PADDING_BYTES bytes of blank \$FF EPROM padding..."
    perl -e "print \"\xFF\" x $PADDING_BYTES" >> "$FINAL_ROM"
    
    NEW_SIZE=$(wc -c < "$FINAL_ROM" | tr -d ' ')
    echo "🚀 Final EPROM File Layout: $NEW_SIZE bytes (Exact 2KB 2716 EPROM Alignment)"
elif [ "$CURRENT_SIZE" -gt "$TARGET_SIZE" ]; then
    echo "⚠️  WARNING: Target code exceeds 2KB EPROM space!"
else
    echo "🏆 Match: Code fits perfectly inside 2KB target boundaries."
fi

echo ""
echo "================================================================================"
echo "🗺️  STEP 3: Structural Symbol Mapping Index Summary"
echo "================================================================================"
if [ -f "$LIST_FILE" ]; then
    echo "📍 Vector Address Table Targets discovered in '$LIST_FILE':"
    echo "--------------------------------------------------------------------------------"
    # Scans the GNU .lis file for core label addresses
    grep -E "RSST|CASLOC|PON:|MONLP:" "$LIST_FILE" | sed 's/^/   /'
    echo "--------------------------------------------------------------------------------"
    echo "🎉 EPROM Binary safely built: $FINAL_ROM"
else
    echo "⚠️  Alert: Listing file '$LIST_FILE' was not generated by assembler."
fi
